<?php

namespace Crm\MainBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChatRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ChatRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array('enabled'=> 1 ), array('created' => 'DESC'));
    }

    public function loadClients()
    {
        $q = $this
            ->createQueryBuilder('c')
            ->leftJoin('c.client','u')
            ->where('u.enabled = 1')
            ->andWhere('u.id is not null')
            ->groupBy('u.id')
            ->orderBy('c.created','DESC')
            ->getQuery();
//        echo $q->getSQL();
//        exit;
        return $q->getResult();
    }

    public function loadMessages($clientId){
        $q = $this
            ->createQueryBuilder('c')
            ->leftJoin('c.client','u')
            ->where('u.enabled = 1')
            ->andWhere('u.id = :user')
            ->orderBy('c.created','DESC')
            ->setParameter(':user' , $clientId)
            ->getQuery();
//        echo $q->getSQL();
//        exit;
        return $q->getResult();
    }
}
