<?php

namespace Crm\MainBundle\Entity;

/**
 * FastOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FastOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
