<?php

namespace Crm\MainBundle\Entity;

/**
 * PassportCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassportCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
