services:
    twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
            - { name: 'twig.extension' }

    app.twig_extension:
        class: Panel\OperatorBundle\Service\TwigExtension
        tags:
            - { name: twig.extension }

